name: Build & Publish Javadocs

on:
  push:
    branches:
      - master

jobs:
  build-javadocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Build Bits-RPS
      - name: Build BitsRPS
        run: mvn clean install

      # Generate Javadocs
      - name: Build Javadocs
        run: mvn javadoc:javadoc

      # Deploy to GitHub Pages
      - name: Deploy Javadocs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs